// <auto-generated />
using System;
using Beecow.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Beecow.Migrations
{
    [DbContext(typeof(BeecowDbContext))]
    [Migration("20210413105236_Add_Product1")]
    partial class Add_Product1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Beecow.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Beecow.Entities.ImagesProduct", b =>
            {
                b.Property<string>("Images_id")
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("Product_images")
                    .HasColumnType("varbinary(max)");

                b.Property<Guid?>("Product_id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("LastSavedTime")
                        .HasColumnType("datetime2");

                b.Property<string>("CreatedUser")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastSavedUser")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Images_id");

                b.HasIndex("Product_id");

                b.ToTable("ImagesProduct");
            });

            modelBuilder.Entity("Beecow.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CustomerId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Beecow.Entities.Product", b =>
            {
                b.Property<Guid>("Product_id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("User_id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Product_title")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Product_short_description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Product_full_description")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Product_price")
                    .HasColumnType("float");

                b.Property<string>("Product_price_currency")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Product_price_discount_value")
                    .HasColumnType("float");

                b.Property<bool>("Product_price_discount_percentage")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Product_unit")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Product_category")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Product_size")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Product_weight")
                    .HasColumnType("float");

                b.Property<string>("Product_weight_unit")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Product_inventory_amount")
                    .HasColumnType("float");

                b.Property<bool>("Product_inventory_adjustment")
                    .HasColumnType("bit");

                b.Property<bool>("Product_status")
                    .HasColumnType("bit");

                b.Property<string>("Product_status")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LastSavedTime")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedUser")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastSavedUser")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Product_id");

                b.ToTable("Product");
            });

            modelBuilder.Entity("Beecow.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Beecow.Entities.ImagesProduct", b =>
            {
                b.HasOne("Beecow.Entities.Product", "Product")
                    .WithMany("ImagesProduct")
                    .HasForeignKey("Product_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Beecow.Entities.Order", b =>
                {
                    b.HasOne("Beecow.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1");
                });

            modelBuilder.Entity("Beecow.Entities.User", b =>
                {
                    b.HasOne("Beecow.Entities.Business", "Business")
                        .WithMany("Users")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
